create table MOCK_DATA (
	id INT,
	item_name VARCHAR(50),
	category VARCHAR(6),
	stock INT
);
insert into MOCK_DATA (id, item_name, category, stock) values (1, 'Syrup - Monin, Amaretta', 'Fruit', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (2, 'Mayonnaise', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (3, 'Fish - Artic Char, Cold Smoked', 'Bakery', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (4, 'Jolt Cola', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (5, 'Wine - Red, Cabernet Sauvignon', 'Fruit', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (6, 'Snails - Large Canned', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (7, 'Cumin - Whole', 'Tech', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (8, 'Pomegranates', 'Bakery', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (9, 'Coffee Cup 12oz 5342cd', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (10, 'Fish - Artic Char, Cold Smoked', 'Fruit', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (11, 'Lid Coffeecup 12oz D9542b', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (12, 'Cheese - Comtomme', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (13, 'Wine - Jaboulet Cotes Du Rhone', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (14, 'Beer - True North Strong Ale', 'Veg', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (15, 'Wine - Cave Springs Dry Riesling', 'Bakery', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (16, 'Creamers - 10%', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (17, 'Celery', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (18, 'Bread - Ciabatta Buns', 'Veg', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (19, 'Ostrich - Fan Fillet', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (20, 'Yogurt - Peach, 175 Gr', 'Fruit', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (21, 'Uniform Linen Charge', 'Bakery', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (22, 'Fish - Halibut, Cold Smoked', 'Veg', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (23, 'Temperature Recording Station', 'Bakery', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (24, 'Rice Pilaf, Dry,package', 'Fruit', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (25, 'Muffin Orange Individual', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (26, 'Chinese Lemon Pork', 'Fruit', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (27, 'Tea - Vanilla Chai', 'Bakery', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (28, 'Pepper - Chipotle, Canned', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (29, 'Juice - Clam, 46 Oz', 'Fruit', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (30, 'Asparagus - Mexican', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (31, 'Chicken - Breast, 5 - 7 Oz', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (32, 'Sea Urchin', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (33, 'Arctic Char - Fillets', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (34, 'Lemonade - Island Tea, 591 Ml', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (35, 'Kumquat', 'Fruit', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (36, 'Ice Cream Bar - Oreo Cone', 'Bakery', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (37, 'Carrots - Jumbo', 'Tech', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (38, 'Syrup - Chocolate', 'Bakery', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (39, 'Truffle - Whole Black Peeled', 'Fruit', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (40, 'Cheese - Cheddar With Claret', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (41, 'Pastry - Trippleberry Muffin - Mini', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (42, 'Soup - Campbells Pasta Fagioli', 'Bakery', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (43, 'Brandy - Bar', 'Fruit', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (44, 'Mussels - Cultivated', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (45, 'Ice Cream - Vanilla', 'Fruit', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (46, 'Wine - Bourgogne 2002, La', 'Fruit', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (47, 'Table Cloth 81x81 White', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (48, 'Wakami Seaweed', 'Bakery', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (49, 'Coconut - Creamed, Pure', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (50, 'Energy Drink - Franks Original', 'Fruit', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (51, 'Stock - Fish', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (52, 'Lemonade - Island Tea, 591 Ml', 'Veg', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (53, 'Nori Sea Weed', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (54, 'Cabbage - Savoy', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (55, 'Sambuca - Ramazzotti', 'Bakery', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (56, 'Tray - 16in Rnd Blk', 'Veg', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (57, 'Bonito Flakes - Toku Katsuo', 'Fruit', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (58, 'Yogurt - Assorted Pack', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (59, 'Knife Plastic - White', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (60, 'Salt - Rock, Course', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (61, 'Compound - Pear', 'Fruit', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (62, 'Shiratamako - Rice Flour', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (63, 'Snapple - Mango Maddness', 'Bakery', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (64, 'Longos - Grilled Chicken With', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (65, 'Wine - George Duboeuf Rose', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (66, 'Glove - Cutting', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (67, 'Vegetable - Base', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (68, 'Poppy Seed', 'Veg', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (69, 'Spinach - Spinach Leaf', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (70, 'Pepper - Gypsy Pepper', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (71, 'The Pop Shoppe - Black Cherry', 'Veg', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (72, 'Mcguinness - Blue Curacao', 'Veg', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (73, 'Basil - Fresh', 'Bakery', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (74, 'Fudge - Chocolate Fudge', 'Veg', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (75, 'Pimento - Canned', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (76, 'Petite Baguette', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (77, 'Clementine', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (78, 'Appetizer - Sausage Rolls', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (79, 'Chestnuts - Whole,canned', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (80, 'Soup - Campbells Pasta Fagioli', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (81, 'Split Peas - Green, Dry', 'Bakery', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (82, 'Wine - Prosecco Valdobiaddene', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (83, 'Eggroll', 'Tech', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (84, 'Beans - Navy, Dry', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (85, 'Langers - Cranberry Cocktail', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (86, 'Ice Cream Bar - Rolo Cone', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (87, 'Eggwhite Frozen', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (88, 'Kellogs All Bran Bars', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (89, 'Cod - Salted, Boneless', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (90, 'Tart - Raisin And Pecan', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (91, 'Beef - Top Sirloin', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (92, 'Sansho Powder', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (93, 'Sole - Dover, Whole, Fresh', 'Fruit', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (94, 'Tea - Herbal I Love Lemon', 'Fruit', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (95, 'Beef - Short Loin', 'Fruit', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (96, 'Lettuce - Baby Salad Greens', 'Veg', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (97, 'Mustard - Seed', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (98, 'Beans - Fine', 'Bakery', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (99, 'Beer - Labatt Blue', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (100, 'Wine - Fino Tio Pepe Gonzalez', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (101, 'Gelatine Leaves - Bulk', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (102, 'Doilies - 10, Paper', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (103, 'Pork - Hock And Feet Attached', 'Fruit', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (104, 'Kohlrabi', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (105, 'Muffin Mix - Carrot', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (106, 'Kirsch - Schloss', 'Bakery', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (107, 'Muffins - Assorted', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (108, 'Banana', 'Bakery', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (109, 'Pastry - Key Limepoppy Seed Tea', 'Fruit', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (110, 'Mikes Hard Lemonade', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (111, 'Bagel - Everything', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (112, 'Foie Gras', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (113, 'Pear - Packum', 'Veg', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (114, 'Lemonade - Strawberry, 591 Ml', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (115, 'Canada Dry', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (116, 'Cake - Dulce De Leche', 'Veg', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (117, 'Lentils - Red, Dry', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (118, 'Pasta - Angel Hair', 'Veg', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (119, 'Oil - Sesame', 'Fruit', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (120, 'Lettuce Romaine Chopped', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (121, 'Puree - Guava', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (122, 'Bok Choy - Baby', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (123, 'Pepper - Paprika, Hungarian', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (124, 'Cabbage - Red', 'Fruit', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (125, 'Thyme - Dried', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (126, 'Sugar - Invert', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (127, 'Clementine', 'Veg', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (128, 'Pork - Butt, Boneless', 'Fruit', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (129, 'Piping - Bags Quizna', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (130, 'Tea - Herbal Sweet Dreams', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (131, 'Bacardi Mojito', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (132, 'Curry Powder', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (133, 'Cheese - Bocconcini', 'Bakery', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (134, 'Sauce - Black Current, Dry Mix', 'Bakery', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (135, 'Vermacelli - Sprinkles, Assorted', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (136, 'Shallots', 'Bakery', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (137, 'Mix - Cappucino Cocktail', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (138, 'Trout - Hot Smkd, Dbl Fillet', 'Tech', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (139, 'Muffin Mix - Chocolate Chip', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (140, 'Beer - Fruli', 'Tech', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (141, 'Pork - Chop, Frenched', 'Bakery', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (142, 'Meldea Green Tea Liquor', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (143, 'Truffle Shells - White Chocolate', 'Fruit', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (144, 'Tea - Grapefruit Green Tea', 'Bakery', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (145, 'Tea - Orange Pekoe', 'Tech', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (146, 'Bread - Raisin Walnut Oval', 'Fruit', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (147, 'Muffin Mix - Raisin Bran', 'Veg', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (148, 'Oil - Olive, Extra Virgin', 'Veg', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (149, 'Turkey Leg With Drum And Thigh', 'Bakery', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (150, 'Ginger - Fresh', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (151, 'Sauce - Black Current, Dry Mix', 'Bakery', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (152, 'Pepper - Cubanelle', 'Tech', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (153, 'Hagen Daza - Dk Choocolate', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (154, 'Extract - Raspberry', 'Veg', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (155, 'Asparagus - White, Canned', 'Fruit', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (156, 'Mushroom - Porcini Frozen', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (157, 'Syrup - Monin, Amaretta', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (158, 'Energy - Boo - Koo', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (159, 'Guava', 'Veg', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (160, 'Juice - Mango', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (161, 'Sun - Dried Tomatoes', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (162, 'Compound - Raspberry', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (163, 'Chips Potato Reg 43g', 'Fruit', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (164, 'Muffin - Bran Ind Wrpd', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (165, 'Salt - Kosher', 'Veg', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (166, 'Cabbage - Nappa', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (167, 'Mix - Cappucino Cocktail', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (168, 'Tomato - Tricolor Cherry', 'Bakery', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (169, 'Pork - Ham Hocks - Smoked', 'Bakery', 1);
insert into MOCK_DATA (id, item_name, category, stock) values (170, 'Ecolab - Hobart Washarm End Cap', 'Fruit', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (171, 'V8 Pet', 'Tech', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (172, 'Wine - Prosecco Valdobienne', 'Fruit', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (173, 'Beer - Blue', 'Fruit', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (174, 'Lobak', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (175, 'Cheese - Swiss', 'Bakery', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (176, 'Flour - Strong Pizza', 'Bakery', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (177, 'Turkey - Breast, Bone - In', 'Fruit', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (178, 'V8 Splash Strawberry Banana', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (179, 'Pork - Belly Fresh', 'Veg', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (180, 'Raspberries - Frozen', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (181, 'Orange - Blood', 'Bakery', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (182, 'Papayas', 'Tech', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (183, 'Halibut - Fletches', 'Bakery', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (184, 'Wine - Hardys Bankside Shiraz', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (185, 'Syrup - Golden, Lyles', 'Tech', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (186, 'Tomatoes - Hot House', 'Tech', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (187, 'Beer - Upper Canada Lager', 'Veg', 2);
insert into MOCK_DATA (id, item_name, category, stock) values (188, 'Chocolate - Milk, Callets', 'Fruit', 3);
insert into MOCK_DATA (id, item_name, category, stock) values (189, 'Water, Tap', 'Veg', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (190, 'Wine - Winzer Krems Gruner', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (191, 'Pasta - Orzo, Dry', 'Veg', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (192, 'Lime Cordial - Roses', 'Tech', 7);
insert into MOCK_DATA (id, item_name, category, stock) values (193, 'Wine - Sauvignon Blanc Oyster', 'Veg', 10);
insert into MOCK_DATA (id, item_name, category, stock) values (194, 'Magnotta Bel Paese Red', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (195, 'Scallops - Live In Shell', 'Tech', 9);
insert into MOCK_DATA (id, item_name, category, stock) values (196, 'Creme De Cacao White', 'Tech', 6);
insert into MOCK_DATA (id, item_name, category, stock) values (197, 'Cookie Dough - Double', 'Bakery', 8);
insert into MOCK_DATA (id, item_name, category, stock) values (198, 'Oil - Food, Lacquer Spray', 'Tech', 5);
insert into MOCK_DATA (id, item_name, category, stock) values (199, 'Urban Zen Drinks', 'Veg', 4);
insert into MOCK_DATA (id, item_name, category, stock) values (200, 'Flour Dark Rye', 'Fruit', 1);
